services:
  mariadb:
    image: mariadb:latest
    ports:
      - 3306:3306
    volumes:
      - ./db-data:/var/lib/mysql
      - ./db-ddl:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: 'captchalot'